### ISSUE TITLE
not thread safe

### ISSUE THREAD

**Issue by horpto** [sonic182/onecache#1]
this library you can use only in one thread.

**Comment by sonic182** [comment]
It is being mainlty used in asnyc code, but it is easy to do it for sync code, just some locks and that's it. Want to contribute? :smile:

**Comment by sonic182** [comment]
@horpto can you provide an example? or could you check with this branch? `feature/thread_safe` from pr: https://github.com/sonic182/onecache/pull/3

**Comment by horpto** [comment]
Hi, i can make pr

**Comment by sonic182** [comment]
> 

Ok nice, you can also continue mine if you want

**Comment by sonic182** [comment]
> Hi, i can make pr

Any updates? If you test my PR and it works, I can merge it and make a new release
